var settings = {
      bridge: {
        capacity: 5,
        chPrefix: 'C',
        chIdxStart: 21
      },
      camera: {
        prefix: 'C',
        idxStart: 11,
        qty: 1,
      },
      lsc: {
        types: [2, 5, [2, 5]],
        prefix: 'COM',
        idxStart: 5,
        curDrvIdxStart: 2,
        portPrefix: 'CN',
        portIdxStart: 1,
        powerPort: '24VDC',
        usbPort: 'USB',
        sixWayPortPrefix: 'C',
        sixWayPortIdxStart: 2,
        triggerPort: 'HD15',
        chPrefix: 'CH',
        chIdxStart: 1
      },
      pc: {
				maxCount: 5
			},
      vision: {
        maxCount: 10,
        cat: {
          bridge: [1, 2, 3],
          direct: [4, 5, 6, 7]
        },
        types: [
          'Vs2D',
          'Vs2D2',
          'Vs2D3',		  
          'Vs2D4',		  
          'Vs2D5',		  
          'Vs2D6',		  
          'Vs2D7',		  
          'Vs2D8',		  
          'Vs2D9',		  
          'Vs2D-IP',
          'Vs2D-IP2',
          'Vs2D-IP3',
          'Vs2D-IP4',
          'Vs2D-IP5',
          'Vs2D-IP6',
          'Vs2D-IP7',
          'Vs2D-IP8',
          'Vs2D-IP9',		  
          'Vs2SPadPkg',
          'Vs2SPadPkg2',
          'Vs3D',
          'Vs3D2',
          'Vs3D3',
          'Vs3D4',
          'Vs3D5',
          'Vs3D6',
          'Vs3D7',
          'Vs3D8',
          'Vs3D9',		  
          'Vs3D3S',
          'Vs3D3S2',
          'Vs3D3S-DIP',
          'Vs3D3S-DIP2',
          'Vs3D5S',
          'Vs3D5S2',
          'Vs3D5S-QFP',
          'Vs3D5S-QFP2',
          'Vs3DBallPadPkg',
          'Vs3DBallPadPkg2',
          'Vs3DBGAPP',
          'Vs3DBGAPP2',
          'Vs3DBGATru',
          'Vs3DBGATru2',
          'Vs3DBtmPkg',
          'Vs3DBtmPkg2',
          'Vs3DJLi',
          'Vs3DJLi2',
          'Vs3DLi',
          'Vs3DLi2',
          'Vs3DLiP-QFP',
          'Vs3DLiP-QFP2',
          'Vs3DMarkLiPkg',
          'Vs3DMarkLiPkg2',
          'Vs3DTO',
          'Vs3DTO2',
          'Vs4SPadPkg',
          'Vs4SPadPkg2',
          'Vs5S',
          'Vs5S2',
          'Vs5S3',
          'Vs5S4',
          'Vs5S5',
          'Vs5S6',
          'Vs5S7',
          'Vs5S8',
          'Vs5S9',		  
          'Vs5SPadPkg',
          'Vs5SPadPkg2',
          'Vs5SPadPkgOrient',
          'Vs5SPadPkgOrient2',
          'Vs5SPro',
          'Vs5SPro2',
          'VsBallPadPkg',
          'VsBallPadPkg2',
          'VsBGAPP',
          'VsBGAPP2',
          'VsBSIR',
          'VsBSIR2',
          'VsCT',
          'VsCT2',
          'VsIF',
          'VsIF2',
          'VsIFP',
          'VsIFP2',
          'VsIPLensPkg',
          'VsIPLensPkg2',
          'VsIPM',
          'VsIPM2',
          'VsIPM3',
          'VsIPM4',
          'VsIPML',
          'VsIPML2',
          'VsIPML3',
          'VsIPML4',
          'VsIPMLP',
          'VsIPMLP2',
          'VsIPMLP3',
          'VsIPMLP4',
          'VsIPMP',
          'VsIPMP2',
          'VsIPMP3',
          'VsIPMP4',
          'VsIPMP5',
          'VsIPMP6',
          'VsLens',
          'VsLens2',
          'VsLensOC',
          'VsLensOC2',
          'VsLensOCP',
          'VsLensOCP2',
          'VsLF',
          'VsLF2',
          'VsLF3',
          'VsLF4',
          'VsLF5',
          'VsLP',
          'VsLP2',
          'VsLP3',
          'VsM',
          'VsM2',
          'VsMeasure',
          'VsMeasure2',
          'VsMeasureDC',
          'VsMeasureDC2',
          'VsML',
          'VsML2',
          'VsMLO',
          'VsMLO2',
          'VsMLOP',
          'VsMLOP2',
          'VsMLOP3',
          'VsMLOP4',
          'VsMLP',
          'VsMLP2',
          'VsMO',
          'VsMO2',
          'VsMOP',
          'VsMOP2',
          'VsMP',
          'VsMP2',
          'VsOC',
          'VsOC2',
          'VsP',
          'VsP2',
          'VsP3',
          'VsP4',
          'VsP5',
          'VsP6',
          'VsP7',
          'VsPad',
          'VsPad2',
          'VsPad3',
          'VsPad4',
          'VsPadPkg',
          'VsPadPkg2',
          'VsPadPkg3',
          'VsPadPkg4',
          'VsPadPkg5',
          'VsPadPkgOrient',
          'VsPadPkgOrient2',
          'VsPC',
          'VsPC2',
          'VsPC3',
          'VsPC4',
          'VsPC5',
          'VsPC6',
          'VsPC7',
          'VsPC-Tray',
          'VsPC-Tray2',
          'VsPP-uC',
          'VsPP-uC2',
          'VsPSI',
          'VsPSI2',
          'VsPSI3',
          'VsPSI4',
          'VsPSI5',
          'VsPSI6',
          'VsPSI7',
          'VsPSI8',
          'VsPSI9',		  
          'VsRDL',
          'VsRDL2',
          'VsSB',
          'VsSB2',
          'VsSideLEDH',
          'VsSideLEDH2',
          'VsSL-FT(L)',
          'VsSL-FT(L)2',
          'VsSL-FT(R)',
          'VsSL-FT(R)2',
          'VsSW',
          'VsSW2',
          'VsTS',
          'VsTS-E',
          'VsTS2',
          'VsTS2-E',
          'VsTS3-E',
          'VsTS4-E',
          'VsTS5-E',
          'VsTS6-E',
          'VsTS-L',
          'VsTS2-L',
        ]
      }
    };